//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectVault.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Images = new HashSet<Image>();
        }
    
        public int P_Id { get; set; }
        public string P_Name { get; set; }
        public string P_Type { get; set; }
        public string P_Intro { get; set; }
        public string P_Sol { get; set; }
        public string P_Result { get; set; }
        public int U_Id { get; set; }
    
        public virtual ICollection<Image> Images { get; set; }
        public virtual User User { get; set; }
    }
}
